import re
import json

def fix_broken_spaces(text):
    if not text: return ""
    
    # Common OCR single letter space patterns in Portuguese
    rep_patterns = [
        (r'\bq\s+uando\b', 'quando'),
        (r'\bd\s+úvida\b', 'dúvida'),
        (r'\bre\s+sposta\b', 'resposta'),
        (r'\bmenin\s+o\b', 'menino'),
        (r'\bmenin\s+a\b', 'menina'),
        (r'\bPer\s+tencia\b', 'Pertencia'),
        (r'\bper\s+tencia\b', 'pertencia'),
        (r'\bquer\s+er\b', 'querer'),
        (r'\bdepress\s+a\b', 'depressa'),
        (r'\bVolteime\b', 'Voltei-me'),
        (r'\bpedid\s+o\b', 'pedido'),
        (r'\ba\s+néis\b', 'anéis'),
        (r'\bdi\s+agnóstico\b', 'diagnóstico'),
        (r'\bPa\s+blo\b', 'Pablo'),
        (r'\bco\s+mum\b', 'comum'),
        (r'\bass\s+ombro\b', 'assombro'),
        (r'\bfísic\s+a\b', 'física'),
        (r'\bdiss\s+o\b', 'disso'),
        (r'\bexperiên\s+cia\b', 'experiência'),
        (r'\best\s+á\b', 'está'),
        (r'\bu\s+m\b', 'um'),
        (r'\bped\s+ra\b', 'pedra'),
        (r'\bheterôn\s+imo\b', 'heterônimo'),
        (r'\btar\s+efa\b', 'tarefa'),
        (r'\bum\s+a\b', 'uma'),
        (r'\bacorda\s+ram\b', 'acordaram'),
        (r'\bRec\s+onheceram-no\b', 'Reconheceram-no'),
        (r'\bOperári\s+o\b', 'Operário'),
        (r'\bs\s+ão\b', 'são'),
        (r'\bo\s+lhos\b', 'olhos'),
        (r'\bpublicado\s+no\b', 'publicado no'),
        (r'\bper\s+íodo\b', 'período'),
        (r'\bsuscetibilidad\s+e\b', 'suscetibilidade'),
        (r'\bq\s+uando\b', 'quando'),
        (r'\bpassavam\b', 'passavam'),
        (r'\bverg\s+onha\b', 'vergonha'),
        (r'\bsenti\s+mento\b', 'sentimento'),
        (r'\bmagro\s+e\s+escuro\.\s*\.\s*E\b', 'magro e escuro... E'),
        (r'\bautocrueldade\b', 'autocrueldade'),
        (r'\bes\s+trangulara\b', 'estrangulara'),
        (r'\bser\s+os\b', 'ser os'),
        (r'\bdisselhes\b', 'disse-lhes'),
        (r'\bpassag\s+em\b', 'passagem'),
        (r'\best\s+e\b', 'este'),
        (r'\bdescon\s*fiança\b', 'desconfiança'),
        (r'\bba\s+nqueiro\b', 'banqueiro'),
        (r'\braciocinaria\b', 'raciocinaria'),
        (r'\brepe\s+nte\b', 'repente'),
        (r'\bmi\s+l\b', 'mil'),
        (r'\bmete\s+u-os\b', 'meteu-os'),
        (r'\bd\s+o\b', 'do'),
        (r'\bdizer\b', 'dizer'),
        (r'\btravés\b', 'través'),
        (r'\bs\s+e\s+apresenta\b', 'se apresenta'),
        (r'\bc\s+omo\b', 'como'),
        (r'\bque\s+brada\b', 'quebrada'),
        (r'\bencontre\s+i\b', 'encontrei'),
        (r'\bpai\s+néis\b', 'painéis'),
        (r'\btra\s+ços\b', 'traços'),
        (r'\btênue\s+c\s+olorido\b', 'tênue colorido'),
        (r'\blábios\s*;\s*tinha\b', 'lábios; tinha'),
        (r'\bmar\s*fim\b', 'marfim'),
        (r'\btranspor\s+tares\b', 'transportares'),
        (r'\bsemelhante\s+as\b', 'semelhante às'),
        (r'\bCoisa\s+inteiramente\b', 'Coisa inteiramente'),
        (r'\bflutuando\b', 'flutuando'),
        (r'\bcorpori\s*ficada\b', 'corporificada'),
        (r'\bfil\s*me\b', 'filme'),
        (r'\bdescon\s*fiar\b', 'desconfiar'),
        (r'\bpro\s*fissional\b', 'profissional'),
        (r'\bincumbencias\b', 'incumbências'),
        (r'\bInteressante\s+6\b', 'interessante é'),
        (r'\bfigu\s*rando\b', 'figurando'),
        (r'\bSo\s*fisticado\b', 'Sofisticado'),
        (r'\bso\s*fisticado\b', 'sofisticado'),
        (r'\bFilho,\s+é\s+filho\b', 'Filho, é filho'),
        (r'\bmeu\s+filho!\b', 'meu filho!'),
        (r'\bd\s+a\s+s\b', 'das'),
        (r'\bu\s+m\s+a\b', 'uma'),
        (r'\bd\s+e\s+u\s+m\b', 'de um'),
        (r'\bveri\s*fica-se\b', 'verifica-se'),
        (r'\bpresença\s+d\s+e\b', 'presença de'),
        (r'\bn\s+o\b', 'no'),
        (r'\bd\s+e\b', 'de'),
        (r'\be\s+m\b', 'em')
    ]
    
    for pat, r in rep_patterns:
        text = re.sub(pat, r, text, flags=re.IGNORECASE)
        
    return text

print("Fix broken spaces ready")
