"""Recover pedagogical emphasis from a font-aware PDF.js preview.

The preview is generated by ``generate_clean_bank.py`` with the corrected
``extract_pdfjs.mjs`` font map.  This script never replaces question content:
it transfers only exact styled spans into the already audited bank, preserving
all manual OCR, paragraph, source and answer-key corrections.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
BANK_PATH = ROOT / "src" / "data" / "questionBank.ts"
SIMULADO_PATH = ROOT / "src" / "data" / "simuladoQuestions.ts"
PREVIEW_PATH = ROOT / "tmp" / "questionBank-markup-preview.ts"
UNDERLINES_PATH = ROOT / "tmp" / "question-underlines.json"

MARKUP_RE = re.compile(r"\*\*(.+?)\*\*", re.DOTALL)
EXISTING_MARKUP_RE = re.compile(r"(\*\*.+?\*\*|<u>.*?</u>)", re.DOTALL)
REFERENCE_RE = re.compile(
    r"\b(?:sublinhad[oa]s?|grif[oa]d[oa]s?|destacad[oa]s?|em destaque|em negrito|assinalad[oa]s?)\b",
    re.IGNORECASE,
)
QUOTED_TARGET_RE = re.compile(r"[“\"]\s*[^”\"\n]{1,160}\s*[”\"]")
UNDERLINE_RE = re.compile(r"\b(?:sublinhad[oa]s?|grif[oa]d[oa]s?)\b", re.IGNORECASE)
STRUCTURAL_RE = re.compile(
    r"^(?:Questão\s+\d+|Português|Verbos|Acessar Lista|"
    r"Texto\s+(?:de apoio\s+)?[IVX\d]+|[A-Ea-e]\)|\d+\))$",
    re.IGNORECASE,
)
NON_PEDAGOGICAL_RE = re.compile(
    r"^(?:responda|Leia atentamente o seguinte texto:?|"
    r"O texto foi adaptado|GABARITO\b|https?://|%[0-9A-F]{2})",
    re.IGNORECASE,
)

# The source PDF itself omits or ambiguously renders these targets even though
# the prompt explicitly refers to a highlighted form. Each replacement was
# checked on the rendered source page and is keyed by list/question/field.
MANUAL_REPLACEMENTS: dict[tuple[str, int, str], list[tuple[str, str]]] = {
    ("pdf_1_fonetica", 18, "readingText"): [("recorde", "**recorde**"), ("Nobel", "**Nobel**")],
    ("pdf_1_fonetica", 19, "readingText"): [
        ("cassino", "**cassino**"), ("mais", "**mais**"), ("beije", "**beije**"), ("Cólquida", "**Cólquida**")
    ],
    ("pdf_1_fonetica", 50, "readingText"): [
        ("amador", "**amador**"), ("amada", "**amada**"), ("desejar", "**desejar**"),
        ("desejada", "**desejada**")
    ],
    ("pdf_1_fonetica", 71, "readingText"): [("o ai que", "o **ai** que"), ("que voa.", "que **voa**.")],
    ("pdf_1_fonetica", 78, "readingText"): [("abelha rainha", "abelha **rainha**")],
    ("pdf_1_fonetica", 81, "readingText"): [
        ("receber a visita", "receber **a** visita"), ("que a convidou", "que **a** convidou"),
        ("irem a casa", "irem **a** casa"), ("iriam a pé", "iriam **a** pé"),
        ("que a casa", "que **a** casa")
    ],
    ("pdf_4_classes_var", 42, "option:D"): [("Sabem tudo", "Sabem <u>tudo</u>")],
    ("pdf_5_classes_invar", 27, "option:B"): [("recordar o que", "recordar <u>o</u> que")],
    ("pdf_6_pronomes", 46, "option:A"): [("Considero-o", "Considero-<u>o</u>")],
    ("pdf_4_classes_var", 33, "option:D"): [("ar que Deus", "ar <u>que</u> Deus")],
    ("pdf_5_classes_invar", 16, "option:D"): [("ar que Deus", "ar <u>que</u> Deus")],
    ("pdf_6_pronomes", 34, "option:B"): [("Por isso, aquele", "Por isso, <u>aquele</u>")],
    ("pdf_6_pronomes", 34, "option:C"): [("evitar essa rebeldia", "evitar <u>essa</u> rebeldia")],
    ("pdf_6_pronomes", 34, "option:D"): [("real, este insabido", "real, <u>este</u> insabido")],
    ("pdf_7", 16, "option:C"): [("que conserve", "que <u>conserve</u>")],
    ("pdf_7", 1, "statement"): [("havia visto", "<u>havia visto</u>")],
    ("pdf_7", 1, "option:C"): [("me revelasse", "me <u>revelasse</u>")],
    ("pdf_7", 1, "option:E"): [("já fizera", "já <u>fizera</u>")],
    ("pdf_2_acentuacao", 60, "option:A"): [("O menino tem", "O menino <u>tem</u>")],
    ("pdf_2_acentuacao", 60, "option:B"): [("Encontro nesse", "<u>Encontro</u> nesse")],
    ("pdf_2_acentuacao", 60, "option:C"): [("ele estivesse", "ele <u>estivesse</u>")],
    ("pdf_2_acentuacao", 60, "option:D"): [("Acompanho o", "<u>Acompanho</u> o")],
    ("pdf_2_acentuacao", 60, "option:E"): [("ele atinja", "ele <u>atinja</u>")],
    ("pdf_2_acentuacao", 63, "readingText"): [("trecho destacado", "trecho a seguir")],
    ("pdf_3_formacao", 84, "readingText"): [("trecho destacado", "trecho a seguir")],
    ("pdf_4_classes_var", 23, "statement"): [("“vitórias-régias”", "“<u>vitórias-régias</u>”")],
    ("pdf_4_classes_var", 37, "option:A"): [("O menino tem", "O menino <u>tem</u>")],
    ("pdf_4_classes_var", 37, "option:B"): [("Encontro nesse", "<u>Encontro</u> nesse")],
    ("pdf_4_classes_var", 37, "option:C"): [("ele estivesse", "ele <u>estivesse</u>")],
    ("pdf_4_classes_var", 37, "option:D"): [("Acompanho o", "<u>Acompanho</u> o")],
    ("pdf_4_classes_var", 37, "option:E"): [("ele atinja", "ele <u>atinja</u>")],
    ("pdf_4_classes_var", 53, "option:A"): [("Mãe.", "<u>Mãe</u>.")],
    ("pdf_4_classes_var", 53, "option:B"): [("Filhos.", "<u>Filhos</u>.")],
    ("pdf_4_classes_var", 53, "option:C"): [("Mulher.", "<u>Mulher</u>.")],
    ("pdf_4_classes_var", 53, "option:D"): [("Marinheiros.", "<u>Marinheiros</u>.")],
    ("pdf_4_classes_var", 53, "option:E"): [("Parentes.", "<u>Parentes</u>.")],
    ("pdf_6_pronomes", 47, "statement"): [("crónica onde um leitor", "crónica <u>onde</u> um leitor")],
    ("pdf_6_pronomes", 54, "option:A"): [("solidariedade, que", "solidariedade<u>,</u> que")],
    ("pdf_6_pronomes", 54, "option:B"): [("sociedade - que", "sociedade <u>-</u> que")],
    ("pdf_6_pronomes", 54, "option:C"): [("culpa, pena", "culpa<u>,</u> pena")],
    ("pdf_6_pronomes", 54, "option:D"): [("fome, surgiram", "fome<u>,</u> surgiram")],
    ("pdf_6_pronomes", 54, "option:E"): [(" - mostra-nos", " <u>-</u> mostra-nos")],
    ("pdf_7", 50, "statement"): [("anos fui germinada por", "anos <u>fui germinada</u> por")],
    ("pdf_7", 61, "option:A"): [("encolhera-se", "encolhera-<u>se</u>")],
    ("pdf_7", 61, "option:B"): [("lembrando-se", "lembrando-<u>se</u>")],
    ("pdf_7", 61, "option:C"): [("tornou-se", "tornou-<u>se</u>")],
    ("pdf_7", 61, "option:D"): [("Se você", "<u>Se</u> você")],
    ("pdf_7", 61, "option:E"): [("passaram-se", "passaram-<u>se</u>")],
    ("pdf_17", 9, "option:A"): [("permita", "<u>permita</u>")],
    ("pdf_17", 9, "option:B"): [("morra", "<u>morra</u>")],
    ("pdf_17", 9, "option:C"): [("volte", "<u>volte</u>")],
    ("pdf_17", 9, "option:D"): [("desfrute", "<u>desfrute</u>")],
    ("pdf_17", 9, "option:E"): [("aviste", "<u>aviste</u>")],
}


def load_export(path: Path, export_name: str) -> tuple[str, list[dict]]:
    source = path.read_text(encoding="utf-8")
    declaration = source.index(f"export const {export_name}")
    payload = source.index(" = ", declaration) + 3
    prefix = source[:payload]
    data = json.loads(source[payload:].rstrip().removesuffix(";"))
    return prefix, data


def write_export(path: Path, prefix: str, data: list[dict]) -> None:
    path.write_text(
        prefix + json.dumps(data, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )


def question_fields(question: dict) -> list[tuple[str, str]]:
    fields = [
        ("readingText", question.get("readingText", "")),
        ("statement", question.get("statement", "")),
    ]
    fields.extend((f"option:{option['letter']}", option.get("text", "")) for option in question.get("options", []))
    return fields


def set_question_field(question: dict, field: str, value: str) -> None:
    if field in {"readingText", "statement"}:
        if value or field in question:
            question[field] = value
        return
    letter = field.split(":", 1)[1]
    for option in question.get("options", []):
        if option.get("letter") == letter:
            option["text"] = value
            return


def structural_spans(question: dict, field: str) -> set[str]:
    spans: set[str] = set()
    if field == "readingText":
        spans.update(line.strip() for line in question.get("readingText", "").splitlines()[:2] if line.strip())
    return spans


def candidates_for(question: dict) -> dict[str, list[str]]:
    result: dict[str, list[str]] = {}
    for field, value in question_fields(question):
        first_lines = structural_spans(question, field)
        candidates: list[str] = []
        for raw_span in MARKUP_RE.findall(value):
            span = re.sub(r"\s+", " ", raw_span).strip()
            if (
                not span
                or span in first_lines
                or "�" in span
                or STRUCTURAL_RE.fullmatch(span)
                or NON_PEDAGOGICAL_RE.match(span)
            ):
                continue
            if len(span) == 1 and (span.isdigit() or span.upper() in set("ABCDE")):
                continue
            candidates.append(span)
        if candidates:
            result[field] = sorted(set(candidates), key=lambda item: (-len(item), item.casefold()))
    return result


def add_markup(text: str, phrase: str, tag: str) -> tuple[str, int]:
    parts = EXISTING_MARKUP_RE.split(text)
    replacements = 0
    for index in range(0, len(parts), 2):
        count = parts[index].count(phrase)
        if not count:
            continue
        parts[index] = parts[index].replace(phrase, f"{tag[0]}{phrase}{tag[1]}")
        replacements += count
    return "".join(parts), replacements


def add_contextual_markup(text: str, phrase: str, context: str, occurrence: int) -> tuple[str, int]:
    """Mark one PDF-located occurrence, never every equal substring in a field."""
    plain = re.sub(r"</?u>|\*\*", "", text)
    context_start = plain.find(context)
    if context_start < 0:
        return text, 0
    relative_starts = [match.start() for match in re.finditer(re.escape(phrase), context)]
    if occurrence >= len(relative_starts):
        return text, 0
    plain_start = context_start + relative_starts[occurrence]
    # At this stage the canonical dataset is unmarked or contains unrelated,
    # balanced spans. Convert the plain offset back to the marked string.
    visible = 0
    marked_start = None
    index = 0
    while index < len(text):
        marker = next((token for token in ("<u>", "</u>", "**") if text.startswith(token, index)), None)
        if marker:
            index += len(marker)
            continue
        if visible == plain_start:
            marked_start = index
            break
        visible += 1
        index += 1
    if marked_start is None:
        return text, 0
    marked_end = marked_start + len(phrase)
    return text[:marked_start] + "<u>" + text[marked_start:marked_end] + "</u>" + text[marked_end:], 1


def transfer_markup(target: dict, preview: dict) -> tuple[int, list[tuple[str, str]]]:
    trigger = " ".join([preview.get("statement", ""), target.get("statement", "")])
    tag = ("<u>", "</u>") if UNDERLINE_RE.search(trigger) else ("**", "**")
    changed = 0
    unmatched: list[tuple[str, str]] = []
    target_values = dict(question_fields(target))

    for field, phrases in candidates_for(preview).items():
        current = target_values.get(field, "")
        for phrase in phrases:
            updated, count = add_markup(current, phrase, tag)
            if count:
                current = updated
                changed += count
            elif phrase not in re.sub(r"</?u>|\*\*", "", current):
                unmatched.append((field, phrase))
        target_values[field] = current

    for field, value in target_values.items():
        set_question_field(target, field, value)
    return changed, unmatched


def normalized_context(text: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"</?u>|\*\*", "", text)).strip().casefold()


def transfer_underlines(target: dict, preview: dict, rows: list[dict]) -> tuple[int, list[str], list[str]]:
    changed = 0
    unmatched: list[str] = []
    ambiguous: list[str] = []
    values = dict(question_fields(target))
    preview_values = dict(question_fields(preview))

    seen_rows: set[tuple[str, str, str]] = set()
    sorted_rows = sorted(rows, key=lambda row: (-len(row["phrase"]), row["phrase"].casefold()))
    for row in sorted_rows:
        phrase = re.sub(r"\s+", " ", row["phrase"]).strip()
        row_key = (phrase, row.get("context", ""), row.get("optionLetter", ""))
        if row_key in seen_rows:
            continue
        seen_rows.add(row_key)
        if (
            not phrase
            or "�" in phrase
            or STRUCTURAL_RE.fullmatch(phrase)
            or NON_PEDAGOGICAL_RE.match(phrase)
            or re.fullmatch(r"[\d\W_]+", phrase)
            or "@" in phrase
        ):
            continue

        already_marked = [
            field for field, value in values.items()
            if f"<u>{phrase}</u>" in value or f"**{phrase}**" in value
        ]
        if already_marked:
            continue

        matching_fields = [
            field for field, value in values.items()
            if phrase in re.sub(r"</?u>|\*\*", "", value)
        ]
        preview_fields = [
            field for field, value in preview_values.items()
            if phrase in re.sub(r"</?u>|\*\*", "", value)
        ]
        hinted_field = None
        option_letter = row.get("optionLetter", "")
        option_field = f"option:{option_letter}" if option_letter else ""
        if option_field in matching_fields:
            hinted_field = option_field
        else:
            context = re.sub(r"^[A-Ea-e]\)?\s+", "", row.get("context", "")).strip()
            normalized_line = normalized_context(context)
            context_matches = [
                field for field in matching_fields
                if len(normalized_line) >= 5
                and (
                    normalized_line in normalized_context(values[field])
                    or normalized_context(values[field]) in normalized_line
                )
            ]
            if len(context_matches) == 1:
                hinted_field = context_matches[0]
            elif len(preview_fields) == 1 and preview_fields[0] in matching_fields:
                hinted_field = preview_fields[0]
        if hinted_field or len(matching_fields) == 1:
            field = hinted_field or matching_fields[0]
            values[field], count = add_contextual_markup(
                values[field], phrase, row.get("context", ""), int(row.get("occurrence", 0))
            )
            if not count and len(matching_fields) == 1 and len(phrase) >= 3:
                values[field], count = add_markup(values[field], phrase, ("<u>", "</u>"))
            changed += count
        elif not matching_fields:
            unmatched.append(phrase)
        else:
            ambiguous.append(phrase)

    for field, value in values.items():
        set_question_field(target, field, value)
    return changed, unmatched, ambiguous


def apply_manual_replacements(question: dict) -> int:
    changed = 0
    values = dict(question_fields(question))
    key_prefix = (question.get("listId"), question.get("questionNumber"))
    for (list_id, number, field), replacements in MANUAL_REPLACEMENTS.items():
        if key_prefix != (list_id, number) or field not in values:
            continue
        value = values[field]
        for old, new in replacements:
            if old in value and new not in value:
                value = value.replace(old, new, 1)
                changed += 1
        values[field] = value
    for field, value in values.items():
        set_question_field(question, field, value)
    return changed


def normalize_markup(question: dict) -> int:
    """Remove empty style runs and join adjacent PDF font fragments."""
    changed = 0
    for field, value in question_fields(question):
        normalized = re.sub(r"\*\*(\s*)\*\*", lambda match: match.group(1), value)
        normalized = re.sub(r"<u>\s*</u>", "", normalized)
        if field == "readingText":
            normalized = re.sub(
                r"\nCom base no texto,\s*responda\s+(?:à|às|a)\s+questão\.?\s*$",
                "",
                normalized,
                flags=re.IGNORECASE,
            )
        if normalized != value:
            set_question_field(question, field, normalized)
            changed += 1
    return changed


def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true", help="write recovered markup to both datasets")
    parser.add_argument("--manual-only", action="store_true", help="apply only PDF-verified deterministic fixes")
    parser.add_argument("--strip-all", action="store_true", help="remove all markup before deterministic recovery")
    parser.add_argument("--underlines-only", action="store_true", help="skip font-based bold recovery")
    parser.add_argument("--compact-fonts", action="store_true", help="recover font marks only for PDFs 16 and 17")
    parser.add_argument("--residual-fonts", action="store_true", help="recover font marks only when a referenced target is still absent")
    args = parser.parse_args()

    bank_prefix, bank = load_export(BANK_PATH, "QUESTION_BANK")
    sim_prefix, simulados = load_export(SIMULADO_PATH, "SIMULADO_QUESTIONS")
    _, preview = load_export(PREVIEW_PATH, "QUESTION_BANK")
    preview_by_key = {(q["listId"], q["questionNumber"]): q for q in preview}
    underline_rows = json.loads(UNDERLINES_PATH.read_text(encoding="utf-8"))
    underlines_by_key: dict[tuple[str, int], list[dict]] = {}
    for row in underline_rows:
        underlines_by_key.setdefault((row["listId"], row["questionNumber"]), []).append(row)

    counters: Counter[str] = Counter()
    unmatched_rows: list[str] = []
    ambiguous_rows: list[str] = []
    for dataset_name, questions in (("bank", bank), ("simulado", simulados)):
        for question in questions:
            if args.strip_all:
                for field, value in question_fields(question):
                    set_question_field(question, field, re.sub(r"</?u>|\*\*", "", value))
            source = preview_by_key.get((question.get("listId"), question.get("questionNumber")))
            if not source:
                continue
            skip_font = (
                args.manual_only
                or args.underlines_only
                or (args.compact_fonts and question.get("listId") not in {"pdf_16", "pdf_17"})
                or (
                    args.residual_fonts
                    and (
                        not REFERENCE_RE.search(question.get("statement", ""))
                        or any(re.search(r"<u>|\*\*", value) for _, value in question_fields(question))
                    )
                )
            )
            changed, unmatched = (0, []) if skip_font else transfer_markup(question, source)
            counters[f"{dataset_name}_questions"] += bool(changed)
            counters[f"{dataset_name}_spans"] += changed
            for field, phrase in unmatched:
                unmatched_rows.append(f"{dataset_name}:{question['id']}:{field}:{phrase}")
            underline_changed, underline_unmatched, underline_ambiguous = (
                (0, [], [])
                if args.manual_only
                else transfer_underlines(
                    question,
                    source,
                    underlines_by_key.get((question.get("listId"), question.get("questionNumber")), []),
                )
            )
            counters[f"{dataset_name}_underline_questions"] += bool(underline_changed)
            counters[f"{dataset_name}_underline_spans"] += underline_changed
            unmatched_rows.extend(
                f"{dataset_name}:{question['id']}:underline:{phrase}"
                for phrase in underline_unmatched
            )
            ambiguous_rows.extend(
                f"{dataset_name}:{question['id']}:underline:{phrase}"
                for phrase in underline_ambiguous
            )
            manual_changed = apply_manual_replacements(question)
            counters[f"{dataset_name}_manual_questions"] += bool(manual_changed)
            counters[f"{dataset_name}_manual_changes"] += manual_changed
            counters[f"{dataset_name}_normalized_fields"] += normalize_markup(question)

    referenced_without_markup: list[str] = []
    for question in bank:
        combined = " ".join(value for _, value in question_fields(question))
        statement = question.get("statement", "")
        if (
            REFERENCE_RE.search(statement)
            and not re.search(r"<u>|\*\*", combined)
            and not QUOTED_TARGET_RE.search(statement)
        ):
            referenced_without_markup.append(question["id"])

    print(json.dumps(dict(counters), ensure_ascii=False, indent=2))
    print(f"unmatched_candidates={len(unmatched_rows)}")
    for row in unmatched_rows[:200]:
        print(f"UNMATCHED {row}")
    print(f"ambiguous_underlines={len(ambiguous_rows)}")
    for row in ambiguous_rows[:200]:
        print(f"AMBIGUOUS {row}")
    print(f"referenced_without_markup={len(referenced_without_markup)}")
    for question_id in referenced_without_markup:
        print(f"NO_MARKUP {question_id}")
    bank_by_id = {question["id"]: question for question in bank}
    for question_id in referenced_without_markup:
        question = bank_by_id[question_id]
        key = (question["listId"], question["questionNumber"])
        print(f"CASE {question_id} :: {question.get('statement', '').replace(chr(10), ' ')[:240]}")
        values = dict(question_fields(question))
        preview_question = preview_by_key.get(key, {})
        for field, phrases in candidates_for(preview_question).items():
            print(f"  FONT {field}: {phrases}")
        for underline_row in underlines_by_key.get(key, []):
            phrase = underline_row["phrase"]
            occurrences = [
                field for field, value in values.items()
                if phrase in re.sub(r"</?u>|\*\*", "", value)
            ]
            print(
                f"  UNDERLINE {phrase!r} -> {occurrences} "
                f"option={underline_row.get('optionLetter', '')!r} context={underline_row.get('context', '')!r}"
            )

    if args.apply:
        write_export(BANK_PATH, bank_prefix, bank)
        write_export(SIMULADO_PATH, sim_prefix, simulados)
        print("Markup recovered in questionBank.ts and simuladoQuestions.ts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
